### ISSUE TITLE
is there a .skip() available?

### ISSUE THREAD

**Issue by jcquarto** [gabrielfalcao/sure#103]
as an in-between passing green and failing red ?

**Comment by timofurrer** [comment]
Unfortunately, there is no such feature available.

**Comment by timofurrer** [comment]
Could you please elaborate a little bit on this feature?

**Comment by timofurrer** [comment]
push

**Comment by timofurrer** [comment]
@jcquarto I'm inclined to remove this issue if no further information is provided. If this would be the case I'm more than happy to re-open this issue once more information is available. 

Thanks :beers:
