### ISSUE TITLE
expect.to.contain returns True always

### ISSUE THREAD

**Issue by codito** [gabrielfalcao/sure#104]
Steps to repro:

```
>>> from sure import expect
>>> expect("hello").to.contain("world")
True
```

Looks like [this](https://github.com/gabrielfalcao/sure/blob/master/sure/__init__.py#L874) may be overwriting `actual` and `expected`, so the comparison is always true.

**Comment by timofurrer** [comment]
Thanks for reporting this! I'll dig into that.

**Comment by timofurrer** [comment]
I've fixed this.

Stay tuned for the next release! :beers:

**Comment by codito** [comment]
thanks Timo!
