### ISSUE TITLE
Merge sphinx documentation and move to RTD

### ISSUE THREAD

**Issue by timofurrer** [gabrielfalcao/sure#115]
We should merge the sphinx documentation branch as soon as possible.
And I think it'd be a good chance to move the main documentation to rtd as well (the current doc server seems to be down)

I've seen that there is a rtd doc online already, but not up-to-date: https://sure.readthedocs.io

@gabrielfalcao what was your plan?

**Comment by gabrielfalcao** [comment]
@timofurrer I just pushed the new docs. I left a `tutorial.rst` hanging in there, I plan on write a step-by-step guide on how I recommend setting up tests in a new project, using test scenarios, setup and teardown methods, the importance of using descriptive single-line docstrings, how using test classes can miseducate developers into creating a comples mesh of test subclasses, and how to go around it using the decorators provided by sure.

I totally rubber-ducked on this ticket and use it as a note for the tutorial :)

**Comment by timofurrer** [comment]
Sure, great! Go for it!
