### ISSUE TITLE
sure seems to break the pytest-xdist plugin

### ISSUE THREAD

**Issue by rogueleaderr** [gabrielfalcao/sure#127]
## Issue Type

Please specify the type of the issue you want to submit:
- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation Report
- [ ] General Enhancement Idea
- [ ] ...
## Versions & Configuration

Please specify the following things:
- version of `sure` 1.4.0
- implementation and version of python 3.5.2 CPython
- operating system MacOS 10.11.6
## Steps to reproduce (Expected and Actual Results)

I created a minimal failing example here: https://github.com/rogueleaderr/xdist_sure

I also crossposted this issue in the pytest-xdist repo: https://github.com/pytest-dev/pytest-xdist/issues/90

**Comment by timofurrer** [comment]
Thanks for the contribution :beers: 
I'll have a look at it as soon as possible.

**Comment by timofurrer** [comment]
Fixed with #129 . We'll release soon!
