### ISSUE TITLE
sure flake8 issue

### ISSUE THREAD

**Issue by rmerkushin** [gabrielfalcao/sure#130]
## Question

Hello, comrades! Thanks for this really cool library!

Flake8 shows me `F401 module imported but unused` error for `import sure`. PyCharm also show `sure` as unused.
Can i bypass this issue? I wan to use git pre-commit hook for flake8 checks without ignoring F401. Sorry for my english :)

**Comment by timofurrer** [comment]
That's a tricky question. 
Without ignoring `F401` on a linter basis you can't get rid of it (wouldn't it be acceptable to disable it for this one import statement line?) ... except with some cheating like:
Do `from sure import expect` and use `expect` only once like: `expect('bar').be.equal('foo')`

**Comment by gabrielfalcao** [comment]
I usually setup my tests this way:

```
setup.py
mymodule/
    __init__.py
tests/
    __init__.py
    unit/
        __init__.py
        test_mymodule.py
    functional/
        __init__.py
        test_mymodule.py
```

Import sure only inside of `tests/__init__.py`, and to prevent the `F401` **flake8** error simply do this:

```python
import sure
sure
```

By doing this you only have to `import sure` once inside of your test module.
The example below considers a codebase that splits tests into unit and functional tests and `sure` never needs to be imported again inside of each test file.

**Comment by timofurrer** [comment]
Thanks @gabrielfalcao .

I'm going to close this issue for now. @rmerkushin Let me know if that already answered your question.
I think there is nothing more we can do for this. However, Gabriels suggestion sounds pretty good to me :tada:

**Comment by gabrielfalcao** [comment]
Thanks @timofurrer

**Comment by rmerkushin** [comment]
Thanks for all answers. I found another one way, just add `# noqa` after `import sure`, and flake8 will ignore any errors on this line. :)

`import sure  # noqa`
