### ISSUE TITLE
matcher cannot handle strings containing % 

### ISSUE THREAD

**Issue by logosity** [gabrielfalcao/sure#134]
## Issue Type
- [X] Bug Report

## Versions & Configuration

sure version 1.4.1; cpython (3.6); ubuntu (14.04) (also asynctest 0.10.0)

## Steps to reproduce (Expected and Actual Results)

Given a simple string match with a '%' on the left hand side:
`'hello%world'.should.be.equal('hello%other')`

(note: answers do not match, this issue only manifests on test failure)
(also note: a similar problem happens if the '%' is only on the right hand side)

One might expect a failure message e.g. `X is 'hello%world' whereas Y is 'hello%other'`

However, this instead results in an error (full stack trace at the bottom of this ticket):
> File "{my home dir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sure/core.py", line 89, in compare_generic
>    m = msg_format % (red(c.current_X_keys), green(c.current_Y_keys))
ValueError: unsupported format character 'w' (0x77) at index 14

Since I encountered this comparing url quoted strings, a workaround for my specific case is to apply `urllib.parse.unquote` to both sides of the comparison, but this seems problematic in the general case of percents in strings - and is initially confusing regardless - so I thought I should open it as an issue. 

#### full stack trace

> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
>   yield
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/asynctest/case.py", line 276, in run
>   self._run_test_method(testMethod)
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/asynctest/case.py", line 328, in _run_test_method
>   self.loop.run_until_complete(result)
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/asynctest/case.py", line 202, in wrapper
>   return method(*args, **kwargs)
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
>   return future.result()
> File "/home/{homedir}/workspace/nimbus-invoke/invoke/test/test_droplet.py", line 383, in test_sends_logstream_url
>   'hello%world'.should.be.equal('hello%other')
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sure/__init__.py", line 384, in wrapper
>   value = func(self, *args, **kw)
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sure/__init__.py", line 650, in equal
>   comparison = DeepComparison(self.obj, what, epsilon).compare()
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sure/core.py", line 230, in compare
>   exp = self.compare_generic(X, Y, **kwargs)
> File "/home/{homedir}/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sure/core.py", line 89, in compare_generic
>   m = msg_format % (red(c.current_X_keys), green(c.current_Y_keys))

**Comment by timofurrer** [comment]
Thanks for the report! :beers: 

I'll have a look at it asap.

**Comment by timofurrer** [comment]
See #135 

I might change a few thing about the implementation in #135 - that's why I didn't merge it immediately.
I'll check again in the evening.

**Comment by timofurrer** [comment]
I've fixed and merged it.

Version **1.4.5** will be released soon!

**Comment by logosity** [comment]
Wow. fantastic turnaround Timo. will grab the next version for sure. thanks for your time and your library. :+1:

**Comment by timofurrer** [comment]
So, release [v1.4.5](https://pypi.python.org/pypi/sure/1.4.5) is finally out! Have fun! 

:beers:
