### ISSUE TITLE
Tests fail on Python 3.7

### ISSUE THREAD

**Issue by hroncok** [gabrielfalcao/sure#142]
## Issue Type

- [x] Bug Report

## Versions & Configuration

- version of `sure` is `master`
- implementation and version of python: CPython 3.7
- operating system: all (but Linux mostly)

## Steps to reproduce (Expected and Actual Results)

See Travis CI results. https://travis-ci.org/gabrielfalcao/sure/jobs/372528183

 * Expected result: tests pass on 3.7
 * Actual result: tests fail on 3.7

## What's going on

I'm trying to bootstrap everything in Fedora on Python 3.7 in order to update to 3.7 in Fedora 29.
The `python-sure` RPM package (that's this `sure`) fails to build because of test failures (other packages are blocked by this). I see you've enabled 3.7 on Travis CI, yet you allow it to fail.

Most notably this is the problem:

```python
AttributeError: module 're' has no attribute '_pattern_type'
```

I'll try to stitch a fix.

BTW See you on [PyCon CZ](https://cz.pycon.org/2018/)  :czech_republic: :snake:  @gabrielfalcao

**Comment by gabrielfalcao** [comment]
Wow, python 3.7 so edgy :) Thanks for this bug report!

**Comment by hroncok** [comment]
Not so much edgy actually. [Ned Deily wrote](https://mail.python.org/pipermail/python-dev/2018-May/153551.html) the following yesterday:

>  Please double-check that there are no critical problems outstanding (...) and that 3.7 is getting exposure and tested with our various platforms and third-party distributions and applications.

It's [scheduled to be released in 1 month](https://www.python.org/dev/peps/pep-0537/).
