### ISSUE TITLE
ReadTheDocs website root url redirects to the wrong destination

### ISSUE THREAD

**Issue by atleta** [gabrielfalcao/sure#145]
## Issue Type

Please specify the type of the issue you want to submit:

- [x ] Bug Report
- [ ] Feature Request
- [ ] Documentation Report
- [ ] General Enhancement Idea
- [ ] ...

## Versions & Configuration
N/A

## Steps to reproduce (Expected and Actual Results)

If you visit http://sure.readthedocs.io/ then you get redirected to http://sure.readthedocs.io/en/master/ and get a 'Permission denied' error page, while the documentation is available at http://sure.readthedocs.io/en/latest/ .

**Comment by timofurrer** [comment]
Where did you find that link? http://sure.readthedocs.io ?
It doesn't seem to be linked anywhere in the source code ..

**Comment by atleta** [comment]
In my browser history :). I'd expect the root url for a web site to just work.

**Comment by timofurrer** [comment]
> I'd expect the root url for a web site to just work.

Me, too. However, this would be an rtd issue rather than a sure issue - Therefore I'll close this issue :)

**Comment by atleta** [comment]
I doubt this is not a configuration issue. I've never run into this myself. E.g. if you go here, it redirects correctly: https://docs.readthedocs.io/ . (I assume you manage the rtd site for sure.)

**Comment by atleta** [comment]
This https://docs.readthedocs.io/en/latest/builds.html#deleting-a-stale-or-broken-build-environment shows that you need to somehow change the value of `READTHEDOCS_VERSION` from `master` to `latest`.
