### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [gabrielfalcao/sure#174]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine tests/test_assertion_builder.py and observe `exceptiont`, however expect to see `exception`.
- Examine docs/source/intro.rst and observe `writen`, however expect to see `written`.
- Examine setup.py and observe `incompatiblities`, however expect to see `incompatibilities`.
- Examine docs/source/about.rst and observe `comparation`, however expect to see `comparison`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/sure/pull/new/bugfix_typos

Thanks.

**Comment by gabrielfalcao** [comment]
It appears that the present issue is somewhat deprecated.
