### ISSUE TITLE
Allow monkey patching of methods already implemented by sure

### ISSUE THREAD

**Issue by gabrielfalcao** [gabrielfalcao/sure#19]
Sure should allow overwritting the `do`, `does` and all the other methods (see below) when using the CPython-compatible syntax sugar (i.e.: `(1).should.be.an(int)`)

* `do`
* `do_not`
* `does`
* `does_not`
* `doesnt`
* `should`
* `should_not`
* `shouldnt`
* `must`

For instance, this test should pass:

```python
import sure

class Foo(object):
    pass

instance = Foo()
instance.do = "anything"

```

**Comment by timofurrer** [comment]
> oh, so you're saying that if the implementation wasn't through @property, we could overwrite the attributes?

Yes, that's true. For example the follow works:

```python
class Foo(object):
    pass

instance = Foo()
instance.within_range = lambda x: x
instance.within_range(1).should.equal(1)
```

That's because `within_range` is an `@assertionmethod` and not an `@assertionproperty`.

@clarete Do you remember what you meant by:

> Maybe we could come up with a helper method. Is it enough? 

I think that this issue could be related to #74 and maybe #44 (didn't had a look at this one yet) as well.
