### ISSUE TITLE
Length inequalities

### ISSUE THREAD

**Issue by fatuhoku** [gabrielfalcao/sure#38]
At present, one can only write

```python
biglist = [1, 2, 3]
biglist.should.have.length_of(3)
```

Whereas it's sometimes useful to have
```python
biglist = [1, 2, 3]
biglist.should.have.length.greater_or_equal_to(3)
```

**Comment by jamesfe** [comment]
I think this might do what you want: https://github.com/gabrielfalcao/sure/blob/master/sure/old.py#L282 

There is some documentation here that may assist too: http://falcao.it/sure/reference.html#assert-the-magnitude-of-objects-with--x--should-be-greater_than-y--and--y--should-be-lower_than-x--as-well-as--x--should-be-greater_than_or_equal_to-y--and--y--should-be-lower_than_or_equal_to-x-

**Comment by timofurrer** [comment]
As @jamesfe pointed out something like that already exists.

I'm closing this issue.
