### ISSUE TITLE
source.should.look_the_same_as(destination) diff

### ISSUE THREAD

**Issue by gabrielfalcao** [gabrielfalcao/sure#52]
I'm currently testing XML comparison, diffs would have been nice [`difflib.Differ`](http://docs.python.org/2/library/difflib.html#differ-example)

**Comment by timofurrer** [comment]
What would `source` and `destination` be in that case? File Object? Paths, given as strings? Arbitrary text and `look_the_same_as` should always use `difflib.Differ`?

**Comment by gabrielfalcao** [comment]
I think we can close this ticket, unless you want to create aliases like `look_the_same_as` which I like.
Here is the current feature: https://github.com/gabrielfalcao/sure/blob/master/sure/__init__.py#L680

**Comment by timofurrer** [comment]
Okay, I like that alias, too. Let's see.

I'm going to close this issue though because the feature already exists in a good enough way.
