### ISSUE TITLE
Asserting that callable does not return given value silently fails

### ISSUE THREAD

**Issue by abeld** [gabrielfalcao/sure#53]
The following should raise an error, but doesn't:

```
import sure
def f():
    return 0

f.when.called_with().should_not.return_value(0)
```

It looks like should_not does not negate when used with called_with()

Use of called_with() and return_value() is documented at http://falcao.it/sure/reference.html#function-when-called_with-arg1--kwarg1-2--should-return_value-value-  so I assume negating it with should_not should also work.

**Comment by jamesfe** [comment]
Just tested this - I think it works likely fixed since 2014.  Recommend closing this ticket?

```
# coding: utf-8

import sure


def test_function_1():
    return 1


def test_function_0():
    return 0

print test_function_1.when.called_with().should.return_value(1)
print test_function_0.when.called_with().should.return_value(0)
```

Output:

```
True
True
```

**Comment by timofurrer** [comment]
@jamesfe thanks!

I'm gonna close this issue since this is already been fixed.
