### ISSUE TITLE
PyPi package has frozen and incorrectly labelled dependencies

### ISSUE THREAD

**Issue by jamielennox** [gabrielfalcao/sure#56]
The pypi package has install dependencies on: 
nose==1.3.0
rednose==0.4.1

Firstly these are not install dependencies they are test dependencies (and rednose probably is neither and belongs in development.txt because it is only referenced by Makefile) 

Secondly, because this is imported directly into setup.py this means that the library is being published with a strict requirement on these versions. This is a similar problem to what we had in HTTPretty so i'm providing the following links which i hope will explain the difference between requirements.txt and setup.py and why it's bad to publish strict version requirements in a setup.py file:
 - http://blog.miguelgrinberg.com/post/the-package-dependency-blues (get's a little lengthy with the whole story).
 - https://caremad.io/blog/setup-vs-requirement/

Thanks for your help.

**Comment by timofurrer** [comment]
I cleaned up the requirements.txt and development.txt.

Thanks! :beers:
