### ISSUE TITLE
that(something).is_greater_than(x) etc

### ISSUE THREAD

**Issue by jonathaneunice** [gabrielfalcao/sure#7]
Just taking the module in for the first time. I really like the readability and clarity of the tests. 

But on my first use, I tried doing some comparison operations. There appears to be a len_greater_than, len_greater_than_or_equals, etc, but the simple comparisons (which I assume would be named is_greater_than, is_greater_than_or_equals, is_less_than, doesnt_equal, and so on) are absent. 

Are they really missing, or am I misunderstanding how to express those tests? I was able to add them with the @that.is_a_matcher decorator, but they seem like core tests that should be available to all. 

The code for these is of course very simple. I would, however, be happy to submit a patch if you like.

**Comment by andrewminer** [comment]
Did these new methods make it into the documentation?  I was just about to open a new issue to ask for these when I found this issue had already been closed...

**Comment by gabrielfalcao** [comment]
Oops, good catch.
