### ISSUE TITLE
Do not allow build for python 3.3 to fail

### ISSUE THREAD

**Issue by timofurrer** [gabrielfalcao/sure#89]
Why is the build for python version 3.3 allowed to fail?

**Comment by gabrielfalcao** [comment]
because I don't use python 3.3 and honestly I would rather not support it.
Do you actively use python 3.3? would you be willing to become responsible to maintain python 3.3 support ? 
What about python 3.4 and 3.5 ?
I find the huge incompatibility between python 3.3, 3.4 and 3.5 very disturbing, and until python truly decides where to take python 3's API,I'll continue to only trust python 2.7

**Comment by timofurrer** [comment]
Honestly, I've never used python 3.3 myself and I'll probably never use it..
I was just wondering why build it but not care about...

I use python 3.4 and 3.5 in some projects which are using `sure` - So I'm interested in python 3 support.
What about supporting python 2.7 and make sure we support at least **one** version of python 3 (newest, most used, ..?) ?
And with that probably multiple python 3 versions are supported because the API is compatible?
I would definitely be able/willing to make sure at least one python 3 version is supported ...

The other thing is that I'm also supporting pypy in some projects and others are doing the same (as you can read in some Issues). What are your thoughts about that?
What about supporting pypy2 as well - of course with some limitations (use of `expect()` instead of monkey patched objects, ...) ?

**Comment by pablasso** [comment]
@gabrielfalcao what are the incompatibilities between 3.3, 3.4 and 3.5?

**Comment by GuyHoozdis** [comment]
> [..] until python truly decides where to take python 3's API,I'll continue to only trust python 2.7
I can understand that.  I've done professional development in Python for years and have stuck with 2.7 for the same reason.  FWIW, my team recently started a project using Python3.5, so we are committing to supporting 2.7 and 3.5.  I've never written/supported an app written using 3.3 or 3.4.

I just submitted a PR (https://github.com/gabrielfalcao/sure/pull/105) that resolves the issue for all the supported versions named in the `tox.ini` file.

**Comment by timofurrer** [comment]
Python 3.3 is now in the travis build matrix and it passes successfully.

I'm going to close this issue. :beers:

**Comment by gabrielfalcao** [comment]
Thanks @timofurrer !!!!
