### ISSUE TITLE
What about python 2.6 support?

### ISSUE THREAD

**Issue by timofurrer** [gabrielfalcao/sure#97]
Is `sure` supposed to support python 2.6 for new releases?
Does anyone rely on python 2.6 support?

Today, python 2.6 is not tested but in the code base are still hacks to support python 2.6 which, in case we do not support 2.6 any longer, could be removed.

**Comment by gabrielfalcao** [comment]
Great question, I would love **not** to support python 2.6 for sure (no pun intended)

**Comment by timofurrer** [comment]
I'd suggest to wait some days .. Maybe someone will insist on 2.6 support. 
If not we could put at [PendingDeprecationWarning](https://docs.python.org/2/library/exceptions.html#exceptions.PendingDeprecationWarning) when using sure with python 2.6. And then remove it in a further version.... or maybe just get rid of it ..

**Comment by gabrielfalcao** [comment]
I love the idea of using that warning, do you want to implement it, or should I?

**Comment by timofurrer** [comment]
I'll do it :)

On Fri, Jan 29, 2016 at 12:49 PM, Gabriel Falcão <notifications@github.com>
wrote:

> I love the idea of using that warning, do you want to implement it, or
> should I?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabrielfalcao/sure/issues/97#issuecomment-176963706>.
>



-- 
*Timo Furrer*

https://github.com/timofurrer
tuxtimo@gmail.com

**Comment by gabrielfalcao** [comment]
amazing :heart_eyes:
